name: C/C++ CI

on:
  push:
    branches: [ master,gh-actions ]
  pull_request:
    branches: [ master, gh-actions ]

jobs:
  build-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: FFmpeg/FFmpeg
          ref: n4.3.1  
      - name: configure
        run: ./configure
     
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
